// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderProcessingApi.Data;

#nullable disable

namespace OrderProcessingApi.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220207202849_added-gateway-names")]
    partial class addedgatewaynames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BundleGatewayProductGateway", b =>
                {
                    b.Property<int>("BundlesId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("BundlesId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("BundleGatewayProductGateway");
                });

            modelBuilder.Entity("OrderProcessingApi.Domain.Database.BundleGateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BundleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Last_Modified");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("OrderProcessingApi.Domain.Database.PlatformGateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Last_Modified");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int")
                        .HasColumnName("Platform_Id");

                    b.Property<string>("PlatformSku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Platform_Sku");

                    b.Property<int>("PlatformType")
                        .HasColumnType("int")
                        .HasColumnName("Platform_Type");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("OrderProcessingApi.Domain.Database.ProductGateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Last_Modified");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gsku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserGatewayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserGatewayId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OrderProcessingApi.Domain.Database.UserGateway", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Auth0_Id");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Created");

                    b.Property<DateTime>("DateLastModified")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date_Last_Modified");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlatformGatewayProductGateway", b =>
                {
                    b.Property<int>("PlatformsId")
                        .HasColumnType("int");

                    b.Property<int>("ProductsId")
                        .HasColumnType("int");

                    b.HasKey("PlatformsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("PlatformGatewayProductGateway");
                });

            modelBuilder.Entity("BundleGatewayProductGateway", b =>
                {
                    b.HasOne("OrderProcessingApi.Domain.Database.BundleGateway", null)
                        .WithMany()
                        .HasForeignKey("BundlesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderProcessingApi.Domain.Database.ProductGateway", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderProcessingApi.Domain.Database.ProductGateway", b =>
                {
                    b.HasOne("OrderProcessingApi.Domain.Database.UserGateway", null)
                        .WithMany("Products")
                        .HasForeignKey("UserGatewayId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("PlatformGatewayProductGateway", b =>
                {
                    b.HasOne("OrderProcessingApi.Domain.Database.PlatformGateway", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OrderProcessingApi.Domain.Database.ProductGateway", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OrderProcessingApi.Domain.Database.UserGateway", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
